# Generated by Django 5.1.4 on 2024-12-25 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nom',
            field=models.CharField(default='Nom par défaut', max_length=255, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='employee',
            name='prenom',
            field=models.CharField(default='Prénom par défaut', max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code employé'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire journalier'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
    ]
