# Generated by Django 5.1.4 on 2024-12-29 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_nom_employee_prenom_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvance',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='salaryadvance',
            constraint=models.UniqueConstraint(condition=models.Q(('approved', True)), fields=('employee', 'year'), name='max_two_advances_per_year'),
        ),
    ]
