# Generated by Django 5.1.4 on 2025-01-01 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_employee_phone_auditlog_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_employees', models.BooleanField(default=False, verbose_name='Peut gérer les employés')),
                ('can_manage_contracts', models.BooleanField(default=False, verbose_name='Peut gérer les contrats')),
                ('can_manage_leaves', models.BooleanField(default=False, verbose_name='Peut gérer les congés')),
                ('can_manage_salaries', models.BooleanField(default=False, verbose_name='Peut gérer les salaires')),
                ('can_manage_recruitment', models.BooleanField(default=False, verbose_name='Peut gérer le recrutement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
