# Generated by Django 5.1.4 on 2025-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_daily_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='documents',
            field=models.ManyToManyField(blank=True, to='core.document', verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prenom',
            field=models.CharField(max_length=255, verbose_name='Prénom'),
        ),
    ]
