# Generated by Django 5.1.4 on 2025-01-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_diversitystats_auditlog_is_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service'),
        ),
    ]
