# Generated by Django 5.1.4 on 2025-01-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_favorite_updated_at_notification_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='cumulative_leave',
            field=models.IntegerField(default=0),
        ),
    ]
