# Generated by Django 5.1.4 on 2025-01-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_is_candidate_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='favorite',
            name='order',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
