# Generated by Django 5.1.4 on 2025-01-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_favorite_options_favorite_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
