# Generated by Django 5.1.4 on 2025-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_training_options_alter_training_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='can_manage_trainings',
            field=models.BooleanField(default=False, verbose_name='Peut gérer la formation'),
        ),
    ]
