# Generated by Django 5.1.4 on 2025-01-16 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_custompermission_can_manage_trainings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name': 'Prime', 'verbose_name_plural': 'Primes'},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name': 'Fiche de paie', 'verbose_name_plural': 'Fiches de paie'},
        ),
        migrations.AddField(
            model_name='bonus',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'Prime de performance'), ('RETENTION', 'Prime de fidélité'), ('SPECIAL', 'Prime exceptionnelle'), ('OTHER', 'Autre')], default='PERFORMANCE', max_length=20, verbose_name='Type de prime'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='reason',
            field=models.TextField(verbose_name='Raison'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Déductions'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='year',
            field=models.IntegerField(verbose_name='Année'),
        ),
    ]
