# Generated by Django 5.1.4 on 2025-01-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_bonus_options_alter_payslip_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='document',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='trial_period_end',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contract',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage')], max_length=50),
        ),
    ]
