# Generated by Django 5.1.4 on 2025-01-17 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_employeeskill_acquired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé')], default='Débutant', max_length=50),
        ),
    ]
