# Generated by Django 5.1.4 on 2025-01-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_skill_acquisition_date_skill_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="L'adresse e-mail doit être unique.", max_length=254, unique=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Désactivé par défaut jusqu'à la confirmation par e-mail.", verbose_name='Compte activé'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est un candidat.", verbose_name='Est un candidat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True, help_text="Indique si l'utilisateur est un employé.", verbose_name='Est un employé'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est un responsable des ressources humaines.", verbose_name='Est un RH'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est un manager.", verbose_name='Est un manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Code à 6 chiffres pour la validation du compte par e-mail.', max_length=6, null=True, verbose_name='Code de validation'),
        ),
    ]
