# Generated by Django 5.1.4 on 2025-01-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='address',
            field=models.TextField(default='Non spécifiée'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(default='Non spécifié', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(default='Non spécifié'),
        ),
    ]
